name: iTransly
values:
  - key: baseUrl
    value: 'http://localhost:3001'
    type: default
    enabled: true
  - key: authToken
    value: ''
    type: secret
    enabled: true
  - key: sessionId
    value: ''
    type: default
    enabled: true
  - key: recordingId
    value: ''
    type: default
    enabled: true
